name: 'Python composite action'
description: 'call a python script from a composite action'
inputs:
  directory-path:
    description: 'directory path as an example input'
    required: true
    default: '${{ github.workspace }}'
  token:
    description: 'github auth token (PAT, github token, or GitHub app token)'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: run python
      shell: bash
      run: | 
        python3 ${{ github.ACTION_PATH }}/logic.py ${{ inputs.directory-path }} ${{ inputs.token }}
